repos:
        - repo: https://github.com/PyCQA/isort 
          rev: 5.8.0
          hooks:
                  - id: isort
                    name: isort (run `git add -u` on failure)
                    description: Sort Python imports.
                    types: ["python"]
        - repo: https://github.com/psf/black
          rev: 21.5b1
          hooks:
                  - id: black
                    name: black (run `git add -u` on failure)
                    description: Format Python files.
                    types: ["python"]
        - repo: https://github.com/PyCQA/flake8
          rev: 3.9.2
          hooks:
                  - id: flake8
                    description: Analyze Python style and complexity.
                    types: ["python"]
        - repo: https://github.com/PyCQA/pydocstyle
          rev: 6.1.1
          hooks:
                  - id: pydocstyle
                    description: Ensure Python docstring best practices.
                    types: ["python"]
