FROM pios:latest

# set environment variables
ENV DOCKER_HW_ID_PATH /dockertools/hwid

# setup docker tools
RUN mkdir /dockertools
COPY src/web/dockertools/setup.sh /dockertools/setup.sh
COPY src/web/dockertools/entrypoint.sh /dockertools/entrypoint.sh
RUN chmod +x /dockertools/setup.sh && \
    chmox +x /dockertools/entrypoint.sh

ENTRYPOINT [ "/dockertools/entrypoint.sh" ]
