version: '3.1'

services:

  db:
    container_name: autopi_db
    build:
      dockerfile: Dockerfile.db
      context: .
    restart: unless-stopped
    env_file:
      - db_public.env
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_INITDB_WALDIR=/log
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    networks:
      - db_net
    volumes:
      - './src/web/database/postgresql.conf:/etc/postgresql/postgresql.conf'
      - db_data:/var/lib/postgresql/data
      - db_log:/log
    secrets:
      - db_password
  
  db_backup:
    container_name: autopi_db_backup
    image: prodrigestivill/postgres-backup-local
    restart: unless-stopped
    user: postgres:postgres
    volumes:
        - /var/opt/pgbackups:/backups # EDIT ME
    links:
        - db
    depends_on:
        - db
    env_file:
      - db_public.env
      - db_backup.env
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_HOST=autopi_db
    networks:
      - db_net
    secrets:
      - db_password

  api:
    container_name: autopi_api
    build:
      dockerfile: Dockerfile.fastapi
      context: .
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - api_net
      - db_net
    volumes:
      - api_log:/log
    env_file:
      - db_public.env
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_HOST=autopi_db
    secrets:
      - db_password

  proxy:
    container_name: autopi_rev_proxy
    build:
      dockerfile: Dockerfile.caddy
      context: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy_net
      - api_net
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
        #- "./caddy_data:/data"
      - proxy_config:/config
      - proxy_data:/data
      - proxy_log:/log


networks:
  db_net:
    internal: true 
  api_net:
    internal: true
  proxy_net:

volumes:
  db_data:
  db_log:
  api_log:
  proxy_config:
  proxy_data:
  proxy_log:

secrets:
  db_password:
    file: .db_password.secret # EDIT ME
