#!/usr/bin/env bash

# ============================
#     install dependencies
# ============================

# Install any necessary python packages
pip3 install -r requirements.txt


# ============================
#   move scripts to /usr/bin
# ============================

cp ./src/scripts/CSM_getip.py /usr/bin/CSM_getip
chmod +x /usr/bin/CSM_getip

cp ./src/scripts/CSM_getssid.py /usr/bin/CSM_getssid
chmod +x /usr/bin/CSM_getssid

cp ./src/scripts/CSM_get_mac.py /usr/bin/CSM_get_mac
chmod +x /usr/bin/CSM_get_mac

cp ./src/scripts/CSM_add_network.py /usr/bin/CSM_add_network
chmod +x /usr/bin/CSM_add_network

cp ./src/scripts/CSM_wpa_country.py /usr/bin/CSM_wpa_country
chmod +x /usr/bin/CSM_wpa_country


# ============================
#      run initial setup
# ============================

# add country information to network discovery system
CSM_wpa_country get 1>/dev/null
if [ $? -ne 0 ]; then
    CSM_wpa_country update US
fi
# add guest network by default
CSM_add_network --no-password --priority=1 CSMguest
